### ISSUE TITLE
AttributeError: module 'dnnlib' has no attribute 'SubmitConfig'

### ISSUE THREAD

**Issue by Young-people** [pbaylies/stylegan2#14]
!python run_training.py --num-gpus=1 --data-dir=./dataset --config=config-f --dataset=lex --mirror-augment=true --metric=none --total-kimg=10000

Traceback (most recent call last):
  File "run_training.py", line 230, in <module>
    main()
  File "run_training.py", line 225, in main
    run(**vars(args))
  File "run_training.py", line 46, in run
    sc        = dnnlib.SubmitConfig()                                          # Options for dnnlib.submit_run().
AttributeError: module 'dnnlib' has no attribute 'SubmitConfig'

![image](https://user-images.githubusercontent.com/20570078/104539510-a7f69d00-5658-11eb-9ea0-a4a99244d7e6.png)

**Comment by dubhestardust** [comment]
There are errors in this version

Try a previous version, such as 90d548243b
